version: '3'

tasks:
  default:
    cmds:
      - task: build

  tidy:
    cmds:
      - go mod tidy

  build:
    deps: [tidy]
    cmds:
      - go build -o consul-docker-operator cmd/consul-docker-operator/main.go
    generates:
      - consul-docker-operator
    silent: false

  clean:
    cmds:
      - rm consul-docker-operator

  docker:build-amd64:
    deps: [tidy]
    cmds:
      - docker build --build-arg BUILD_ARCH=amd64 .

  docker:build-arm64:
    deps: [tidy]
    cmds:
      - docker build --build-arg BUILD_ARCH=arm64 .
